[package]
name = "coin_tracker"
version = "0.1.0"
authors = ["Moritz Drexl <mdrexl@fastmail.fm"]
edition = "2021"
rust-version = "1.65"

[dependencies]
electrum-client = "0.13.0"
rustls = "0.20.8"

egui = "0.21.0"
eframe = { version = "0.21.0", default-features = false, features = ["default_fonts", "glow", "persistence" ] }
serde = { version = "1", features = ["derive"] }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"
wasm-bindgen-futures = "0.4"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2

[patch.crates-io]
