[package]
name = "coin_tracker"
version = "0.1.0"
authors = ["Moritz Drexl <mdrexl@fastmail.fm"]
edition = "2021"
rust-version = "1.65"

[dependencies]
electrum-client = "0.13.0"
rustls = "0.20.8"
egui = "0.21.0"
eframe = { version = "0.21.0", default-features = false, features = ["default_fonts", "glow", "persistence" ] }
serde = { version = "1", features = ["derive"] }
tracing-subscriber = "0.3"
